name: Workflow
on: [push, pull_request]
jobs:
  react-app-workflow:
    uses: nciocpl/cgov-react-app-playground/.github/workflows/workflow.yml@c23ca0950d13f3fdb9b6d23de8f9b2ccb342d16b
    secrets: inherit
